CREATE TABLE IF NOT EXISTS usuario(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(255) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    
    PRIMARY KEY(id),
    UNIQUE KEY(email)
);

